export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_PLAYING = 'SET_PLAYING';
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN';
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';
export const SET_RANDOM_PLAYLIST = 'SET_RANDOM_PLAYLIST';
export const SET_MODE = 'SET_MODE';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
